[versions]
compileSdk = "33"
targetSdk = "33"
minSdk = "24"

androidGradlePlugin = "7.2.2"
kotlinGradlePlugin = "1.7.10"
detektGradlePlugin = "1.22.0-RC2"

kotlinComposeCompiler = "1.3.0"
androidDesugaring = "1.1.5"

androidxCore = "1.7.0"
androidxAppCompat = "1.4.1"
androidxLifecycle = "2.4.1"
androidxFragment = "1.5.2"
androidxSecurity = "1.1.0-alpha03"
androidxComposeActivity = "1.5.1"
androidxCompose = "1.2.1"
androidxRoom = "2.4.3"

googleMaterial = "1.6.1"

retrofit = "2.9.0"
okHttp = "4.10.0"
moshi = "1.14.0"

coroutinesAndroid = "1.6.4"

dagger2 = "2.43.2"

orbit = "4.3.2"

beagle = "2.8.3"
timber = "5.0.1"

detektComposeRules = "1.2.2"

[libraries]

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
android-gradle-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "androidGradlePlugin" }
android-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugaring" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-security = { module = "androidx.security:security-crypto", version.ref = "androidxSecurity"}

androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxComposeActivity"}
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidxCompose" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidxCompose" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxCompose" }
androidx-compose-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "androidxCompose"}

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom"}
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }

arturbosch-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektGradlePlugin" }

google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
google-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger2" }
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger2" }

pandulapetor-beagle = { module = "io.github.pandulapeter.beagle:ui-drawer", version.ref = "beagle" }
pandulapetor-beagle-noop = { module = "io.github.pandulapeter.beagle:noop", version.ref = "beagle" }

pandulapetor-beagle-okhttp = { module = "io.github.pandulapeter.beagle:log-okhttp", version.ref = "beagle" }
pandulapetor-beagle-okhttp-noop = { module = "io.github.pandulapeter.beagle:log-okhttp-noop", version.ref = "beagle" }

pandulapetor-beagle-logger = { module = "io.github.pandulapeter.beagle:log", version.ref = "beagle" }
pandulapetor-beagle-logger-noop = { module = "io.github.pandulapeter.beagle:log-noop", version.ref = "beagle" }

squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
squareup-okhttp-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
squareup-moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
squareup-moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinGradlePlugin"}
jetbrains-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroid"}

jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

orbit-mvi-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit"}
orbit-mvi-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
orbit-mvi-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }

kode-detekt-rules-compose = { module = "ru.kode:detekt-rules-compose", version.ref = "detektComposeRules" }

[bundles]

androidx-compose = [
    "androidx-compose-material", "androidx-compose-animation",
    "androidx-compose-tooling", "androidx-compose-activity"
]

orbit-mvi = ["orbit-mvi-core", "orbit-mvi-viewmodel", "orbit-mvi-compose"]

[plugins]

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektGradlePlugin" }
